version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: portfolio-db
    ports:
      - "8001:5432"
    environment:
      POSTGRES_DB: portfolioDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  quarkus-api:
    build: .
    container_name: portfolio-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/portfolioDB
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: 1234
      QUARKUS_PROFILE: dev