services:
  - type: web
    name: portfolio-api
    env: native
    buildCommand: ./gradlew build -Dquarkus.package.type=native --no-daemon
    startCommand: ./build/portfolio-api-*-runner
    plan: free
    region: oregon