services:
  - type: web
    name: portfolio-api
    env: docker
    region: oregon
    plan: free
    buildCommand: |
      ./gradlew build -Dquarkus.package.type=native --no-daemon
      docker build -t portfolio-api .
    startCommand: ./application