services:
  - type: web
    name: portfolio-api
    runtime: docker
    dockerfile: Dockerfile
    # Build command simplificado (o build já está no Dockerfile)
    buildCommand: echo "Build via Dockerfile multistage"
    env: docker
    plan: free
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1

    healthCheckPath: /q/health/live
    healthCheckTimeoutSeconds: 10
    healthCheckIntervalSeconds: 30

    numInstances: 1
    cpu: 0.5
    memoryMB: 512

    envVars:
      - key: QUARKUS_PROFILE
        value: prod
      - key: QUARKUS_DATASOURCE_JDBC_URL
        value: jdbc:postgresql://portfolio-db:5432/portfolioDB
      - key: QUARKUS_DATASOURCE_USERNAME
        value: postgres
      - key: QUARKUS_DATASOURCE_PASSWORD
        fromDatabase:
          name: portfolio-db
          property: password
      - key: PUBLIC_KEY_PEM
        sync: false  # Será configurado manualmente
      - key: PRIVATE_KEY_PEM
        sync: false
      - key: INITIAL_API_KEY
        sync: false
      - key: QUARKUS_HTTP_CORS_ORIGINS
        value: ${CORS_ORIGINS}  # Configure no painel se precisar

    # Deploy hooks (opcional)
    deployHooks:
      postDeploy:
        - curl -X GET http://localhost:8080/q/health/