services:
  - type: web
    name: portfolio-api
    runtime: docker
    dockerfile: Dockerfile
    env: docker
    buildCommand: ./gradlew clean build -Dquarkus.package.type=native
    healthCheckPath: /q/health/live
    envVars:
      - key: QUARKUS_PROFILE
        value: prod
      - key: QUARKUS_DATASOURCE_JDBC_URL
        value: jdbc:postgresql://portfolio-db:5432/portfolioDB
      - key: QUARKUS_DATASOURCE_USERNAME
        value: postgres
      - key: QUARKUS_DATASOURCE_PASSWORD
        fromDatabase:
          name: portfolio-db
          property: password

      - key: INITIAL_USER_EMAIL
        sync: false
      - key: INITIAL_USER_PASSWORD
        sync: false
      - key: INITIAL_API_KEY
        sync: false

    plan: free
    numInstances: 1
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1

  - type: postgres
    name: portfolio-db
    plan: free
    databaseName: portfolioDB
    user: postgres
    ipAllowList: []